POST localhost:8001/client
Content-Type: application/json

{
  "clientEmail" : "test@email.com",
  "clientPassword" : "qwer1234@",
  "clientName" : "tester",
  "clientBirth" : "2024-06-16T00:00:00",
  "clientPhoneNumber" : "01066666808"
}